version: '3.8'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: 123321